### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: length=64; index=64

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#146]
From user report. I think this might be happening scanning a QR-Code that is not a valid Address.

```
java.lang.RuntimeException: Unable to resume activity {org.walleth/org.walleth.activities.CreateAccountActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=27011, result=-1, data=Intent { (has extras) }} to activity {org.walleth/org.walleth.activities.CreateAccountActivity}: java.lang.StringIndexOutOfBoundsException: length=64; index=64
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2969)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2998)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
at android.app.ActivityThread.access$1000(ActivityThread.java:169)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=27011, result=-1, data=Intent { (has extras) }} to activity {org.walleth/org.walleth.activities.CreateAccountActivity}: java.lang.StringIndexOutOfBoundsException: length=64; index=64
at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2956)
... 13 more
Caused by: java.lang.StringIndexOutOfBoundsException: length=64; index=64
at org.kethereum.erc55.ERC55Kt.withERC55Checksum(ERC55.kt:17)
at org.walleth.activities.CreateAccountActivity.setAddressFromExternalApplyingChecksum(CreateAccountActivity.kt:138)
at org.walleth.activities.CreateAccountActivity.onActivityResult(CreateAccountActivity.kt:126)
at android.app.Activity.dispatchActivityResult(Activity.java:5643)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
... 14 more
```

**Comment by akostadinov** [comment]
Hi, I think I've got both issues while trying to scan a code but IIRC once it was even before I actually could see camera turned on and on the other occasion it was probably shortly after I saw camera turned on.

I don't think at the time of the issue there was any barcode in the sight of the scanner. If it can return some garbage data while not pointed at anything, then your assumption might make sense. My first thought was that app has troubles interacting with camera.

**Comment by akostadinov** [comment]
Or some timeout. Phone not very fast but default camera app never crashed. Phone is generally stable for other usage. It even didn't crash when I tried the integrated light client although it was hot and slow until it caught up with the blocks.

**Comment by ligi** [comment]
Thanks! There was a result from the scanner - cannot see what exactly - but I can validate the input in this path and also include what was scanned in the error message. This should fix the problem and give information on what was actually scanned. Sorry for the problem and thanks so much for providing the report!
