### ISSUE TITLE
Crash when swiping app away on Android 8.1

### ISSUE THREAD

**Issue by cfabio** [walleth/walleth#212]
Walleth version 0.31 (installed from F-Droid)
Android version 8.1.0 (LineageOS 15.1)

Swiping Walleth away from the "recently used apps tab" makes it crash with the following error message: Walleth stopped

**Comment by ligi** [comment]
Thanks - can you by any chance provide a log?

**Comment by ligi** [comment]
Never mind - think I could just reproduce it with a 8.1 emulator - seems to be a 8.1 specific problem:

```
03-04 17:09:49.756  4110  4110 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.walleth.App: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.walleth/.geth.services.GethTransactionSigner }: app is in background uid UidRecord{f4d727e u0a82 SVC  idle change:uncached procs:1 seq(0,0,0)}
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.walleth/.geth.services.GethTransactionSigner }: app is in background uid UidRecord{f4d727e u0a82 SVC  idle change:uncached procs:1 seq(0,0,0)}
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at org.walleth.geth.GethInitContentProvider$onCreate$1.invoke(GethInitContentProvider.kt:22)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at org.walleth.geth.GethInitContentProvider$onCreate$1.invoke(GethInitContentProvider.kt:16)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at org.walleth.App.onCreate(App.kt:150)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
03-04 17:09:49.756  4110  4110 E AndroidRuntime: 	... 8 more
```

will care for a fix - thanks for reporting

**Comment by cfabio** [comment]
That is exactly the same error I am getting, was about to post the exact same log but you were faster.

**Comment by ligi** [comment]
sorry for that - was just trying to reproduce on my daily driver first - issue is not happening there - then had the hinge with 8.1 and voila ..

**Comment by cfabio** [comment]
No problem, thanks for developing and supporting this great app.

**Comment by ligi** [comment]
fixed - will be available with 0.34 - thanks for reporting - should really work on #167 so you do not have to kill the app in the first place ;-)
