### ISSUE TITLE
Can't run the app from Android Studio on Android 8.0 (either hardware or virtual)

### ISSUE THREAD

**Issue by Devilmoon** [walleth/walleth#259]
Hi everyone,

I've cloned the master branch yesterday and have been trying to run it from Android Studio with no luck so far. Attaching the debugger to the app running either on my OnePlus 3T running Android 8.0 or on a virtual Pixel 2XL (running 8.0 as well) returns the following error:

```E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                  Process: org.walleth.offline, PID: 31417
                  java.lang.SecurityException: Permission denied (missing INTERNET permission?)
                      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
                      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
                      at java.net.InetAddress.getAllByName(InetAddress.java:787)
                      at okhttp3.Dns$1.lookup(Dns.java:40)
                      at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
                      at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
                      at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
                      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
                      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
                      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                      at java.lang.Thread.run(Thread.java:764)
                   Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                      at libcore.io.Linux.android_getaddrinfo(Native Method)
                      at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
                      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
                      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) 
                      at java.net.InetAddress.getAllByName(InetAddress.java:787) 
                      at okhttp3.Dns$1.lookup(Dns.java:40) 
                      at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185) 
                      at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149) 
                      at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) 
                      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214) 
                      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) 
                      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) 
                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                      at java.lang.Thread.run(Thread.java:764) 
                   Caused by: android.system.ErrnoException: android_getaddrinfo failed: EACCES (Permission denied)
                      at libcore.io.Linux.android_getaddrinfo(Native Method) 
                      at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58) 
                      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122) 
                      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) 
                      at java.net.InetAddress.getAllByName(InetAddress.java:787) 
                      at okhttp3.Dns$1.lookup(Dns.java:40) 
                      at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185) 
                      at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149) 
                      at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) 
                      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214) 
                      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) 
                      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) 
                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                      at java.lang.Thread.run(Thread.java:764) 
```

Unfortunately I have no way of giving the app internet permission as the stack trace suggests because it crashes as soon as it is loaded onto the phone.

Is this a know bug with Android Studio? Is there a way to fix this? is master currently unstable and so should I clone some other branch/release?

Thanks in advance!

**Comment by Devilmoon** [comment]
For anyone interested, I resolved this issue by adding the line 
`<uses-permission android:name="android.permission.INTERNET"/>`
to AndroidManifest.xml

**Comment by ligi** [comment]
the better solution is to not select the offline flavor but the online flavor. The offline flavor still has some problems and the online flavor is most likely what you want
