### ISSUE TITLE
Intent Crashes App (Denial of Service)

### ISSUE THREAD

**Issue by mateuszk87** [walleth/walleth#318]
# Attack

## Description
The IntentHanderActivity crashes the whole app, when no intent data is provided. 

## Reproduction
```
adb shell am start -n org.walleth/org.walleth.activities.IntentHandlerActivity
```

```
12-12 12:33:05.059 30003 30003 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.walleth/org.walleth.activities.IntentHandlerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at org.walleth.activities.IntentHandlerActivity.onCreate(IntentHandlerActivity.kt:45)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
12-12 12:33:05.059 30003 30003 E AndroidRuntime: 	... 10 more
12-12 12:33:05.060   733  1273 W ActivityManager:   Force finishing activity org.walleth/.activities.IntentHandlerActivity
12-12 12:33:05.065   733  1273 W ActivityManager:   Force finishing activity org.walleth/.activities.MainActivity
```

## Impact
A malicious app could frequently send the mentioned intent in order to make the app unusable. Therefore, the user would not be able to access walleth or backup key material via the app.

**Comment by ligi** [comment]
Thanks for the Report! I will fix it but do not yet see the impact. How would this be different from the "malicious" app starting some other successful intent?

**Comment by mateuszk87** [comment]
True :) The DoS aspect is a little bit "constructed".

**Comment by ligi** [comment]
Thanks anyway - I really appreciate people having a deeper look at the app!
