### ISSUE TITLE
setPreviewTexture failed

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#322]
```
java.io.IOException: setPreviewTexture failed
at android.hardware.Camera.setPreviewTexture(Native Method)
at org.walleth.activities.qrscan.Videographer$openCamera$1.run(Videographer.kt:105)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

Android Version: 7.1.1
Phone Model: ZTE BLADE A320

**Comment by ligi** [comment]
Cannot reproduce the problem - trying this workaround: https://stackoverflow.com/a/38808206/322642
