### ISSUE TITLE
Input is too large to put in byte array of size 32

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#365]
just got this as a user report:

```
java.lang.RuntimeException: Input is too large to put in byte array of size 32
at org.kethereum.extensions.BigIntegerKt.toBytesPadded(BigInteger.kt:23)
at org.kethereum.wallet.WalletKt.createWallet(Wallet.kt:45)
at org.kethereum.wallet.WalletFileKt.generateWalletFile(WalletFile.kt:52)
at org.kethereum.keystore.api.FileKeyStore.addKey(FileKeyStore.kt:39)
at org.kethereum.keystore.api.FileKeyStore.addKey(FileKeyStore.kt:45)
at org.walleth.activities.CreateAccountActivity$onCreate$4.onClick(CreateAccountActivity.kt:98)
at android.view.View.performClick(View.java:4442)
at android.view.View$PerformClick.run(View.java:18471)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ligi** [comment]
hm - that is really strange - I generated a lot of burner wallets and never had this problem. But there is randomness in generating the key - perhaps the chance to generate such a key is very very low. Could try to generate huge amounts of keys on a PC with the same code to see if I can reproduce it this way.
