### ISSUE TITLE
problem scanning QR-Codes with Lenovo TB-X103F

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#382]
```
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
    at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
    at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
    at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
    at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
    at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:64)
    at org.walleth.activities.qrscan.Scanner.decode(Scanner.kt:32)
    at org.walleth.activities.qrscan.Scanner.access$decode(Scanner.kt:10)
    at org.walleth.activities.qrscan.Scanner$scan$1.invoke(Scanner.kt:12)
    at org.walleth.activities.qrscan.Scanner$scan$1.invoke(Scanner.kt:10)
    at org.walleth.activities.qrscan.Videographer$capture$1.onPreviewFrame(Videographer.kt:81)
    at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1150)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by ligi** [comment]
cause here: https://github.com/zxing/zxing/issues/1170
