### ISSUE TITLE
Parameter specified as non-null is null

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#413]
seeing this in reports:

```
 java.lang.RuntimeException: Unable to start service org.walleth.dataprovider.DataProvidingService@6c4ab8 with null: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3368)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter intent
	at org.walleth.dataprovider.DataProvidingService.onStartCommand(DataProvidingService.kt)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
	... 8 more
```

context: 

https://stackoverflow.com/questions/55085449/android-service-crash-when-use-kotlin-language/55086510
https://stackoverflow.com/questions/55085449/android-service-crash-when-use-kotlin-language/55086510

**Comment by ligi** [comment]
upstream bug:
https://issuetracker.google.com/issues/144442247
