### ISSUE TITLE
Import of JSON file exported from MIST crashes walleth

### ISSUE THREAD

**Issue by soldier9945** [walleth/walleth#439]
Hello,

I was recently re-testing walleth and wanted to import an address with <1ETH to give walleth another try (until now the best ETH wallet on Android in my opinion, at least from a privacy point of view).

I tried to import a UTC--..... file that is, for what I remember, a JSON file that should be encrypted with a password. The password I have works as I could access that address using the same JSON file on myetherwallet.com. But when importing the file in walleth, I got an app crashed warning, with no trace of that address after that message.

I tried multiple times before importing it manually by typing the private key in...

I'm not sure how to communicate this UTC--... file or if only some part can identify the version or format of it that could help fix this import issue. I'll gladly provide some info if someone knows how to be more precise.

Thank you!

**Comment by ligi** [comment]
Thanks for the report. Is there any way you can send me the crash report for the crash?

**Comment by soldier9945** [comment]
`file: /data/user/0/org.walleth/files/0.48.2-1583748897150.tracedroid
Android Version: 9
Phone Model: FP3
TraceDroid Version: 1.1
TraceDroid extra: 
Stacktrace: 
 java.lang.OutOfMemoryError: Failed to allocate a 268435472 byte allocation with 12582912 free bytes and 187MB until OOM, max allowed footprint 17255400, growth limit 201326592
	at org.bouncycastle.crypto.generators.SCrypt.SMix(Unknown Source:22)
	at org.bouncycastle.crypto.generators.SCrypt.MFcrypt(Unknown Source:23)
	at org.bouncycastle.crypto.generators.SCrypt.generate(Unknown Source:44)
	at org.kethereum.crypto.impl.kdf.SCryptImpl.derive(SCryptImpl.kt:5)
	at org.kethereum.wallet.WalletKt.generateDerivedScryptKey(Wallet.kt:78)
	at org.kethereum.wallet.WalletKt.decrypt(Wallet.kt:120)
	at org.kethereum.wallet.WalletFileKt.loadKeysFromWalletJsonString(WalletFile.kt:68)
	at org.walleth.accounts.ImportKeyActivity$doImport$1$importKey$1.invokeSuspend(ImportKeyActivity.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Log: 
 0 D: Writing unhandled exception to: /data/user/0/org.walleth/files/0.48.2-1583748897150.tracedroid
1 I: problem fetching data - are we online? com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
2 I: setting search term 2 
3 I: setting search term 
4 I: setting search term 2 
5 I: setting search term 
6 I: problem fetching data - are we online? com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
7 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler`

**Comment by soldier9945** [comment]
Here's the JSON file with **$XYZ_VALUE** replaced for privacy:

`{"address":"$ADDRESS_VALUE","crypto":{"cipher":"aes-128-ctr","ciphertext":"**$CIPHERTEXT_VALUE**","cipherparams":{"iv":"**$IV_VALUE**"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"**$SALT_VALUE**"},"mac":"**$MAC_VALUE**"},"id":"**$ID_VALUE**","version":3}`

**Comment by ligi** [comment]
I could fix the crash - unfortunately importing the key will still not work. The RAM of the phone you have is just not enough to deal with keys that have such a high n. So you need to convert the key to e.g. ecdsa on a PC first. Thanks again for reporting!

**Comment by soldier9945** [comment]
That's unfortunate, these JSON's come straight from the Mist official Ethernet Wallet from ~2018. Well, I'll look out for a way to convert them to ECDSA securely.

**Comment by raymoo** [comment]
Would it still crash for a phone with enough RAM?
