### ISSUE TITLE
Export Key, Account converted to watch only.

### ISSUE THREAD

**Issue by citizenserious** [walleth/walleth#528]
App from F-Droid version 0.50.2
Android 11 Lineage 18.1

1. I created a "Create Key with password"
2. Then I added (don't ask why) under "Watch Only" the same adress of the created wallet.
Result: The 1. created account disappeared and there now only is the "watch only" one. When filtering the account list after "with key" it still shows me the "watch only" account but still not the 1. one created. When I click on the edit button of the "watch only" account it still shows me the option to Export the key, when clicking on it the app crashes and this is the report output:

file: /data/user/0/org.walleth/files/0.50.2-1622724325276.tracedroid
Android Version: 11
Phone Model: SM-G960F\nTraceDroid Version: 4.1\nStacktrace: java.lang.IllegalArgumentException: getPasswordForAccountType() must be called for ACCOUNT_TYPE_PIN_PROTECTED, ACCOUNT_TYPE_PASSWORD_PROTECTED or ACCOUNT_TYPE_BURNER but was watchonly
 at org.walleth.util.security.PasswordProviderKt.getPasswordForAccountType(PasswordProvider.kt:25)
 at org.walleth.accounts.ExportKeyActivity$onCreate$1.invokeSuspend(ExportKeyActivity.kt:63)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7660)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
\nLog:  3 current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
I setting search term 
I setting search term 2 
I setting search term 
I setting search term 2 
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
3 Writing unhandled exception to: /data/user/0/org.walleth/files/0.50.2-1622724325276.tracedroid
file: /data/user/0/org.walleth/files/0.50.2-1622724321903.tracedroid
Android Version: 11
Phone Model: SM-G960F\nTraceDroid Version: 4.1\nStacktrace: java.lang.IllegalArgumentException: getPasswordForAccountType() must be called for ACCOUNT_TYPE_PIN_PROTECTED, ACCOUNT_TYPE_PASSWORD_PROTECTED or ACCOUNT_TYPE_BURNER but was watchonly
 at org.walleth.util.security.PasswordProviderKt.getPasswordForAccountType(PasswordProvider.kt:25)
 at org.walleth.accounts.ExportKeyActivity$onCreate$1.invokeSuspend(ExportKeyActivity.kt:63)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7660)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
\nLog:  3 current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
I setting search term 
I setting search term 2 
I setting search term 
I setting search term 2 
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
I setting search term 
I setting search term 2 
I setting search term 
I setting search term 2 
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
W Problem with JSON from EtherScan: Value Max rate limit reached, please use API Key for higher rate limit at result of type java.lang.String cannot be converted to JSONArray
3 Writing unhandled exception to: /data/user/0/org.walleth/files/0.50.2-1622724321903.tracedroid

so it would be quite nice to somehow get the key, or change the account back to a not only "watche only" one, I never deleted the 1. one just added a 2. with the same key as a watch only.
Thanks guys.

**Comment by ligi** [comment]
Thanks for the report! Did you backup the key before?

**Comment by citizenserious** [comment]
> 
> 
> Thanks for the report! Did you backup the key before?

unfortunately I did not...

**Comment by ligi** [comment]
dam - is your phone rooted?

**Comment by citizenserious** [comment]
> 
> 
> dam - is your phone rooted?

Yes it is (: 
Anyway the wallet carries a very small amount, so it's not really bad.

**Comment by ligi** [comment]
"Kleinvieh macht auch mist" ;-)

even if it is just a small amount now - it could be worth a lot in the future ;-)
so better save it now than to cry later ..
If your phone is rooted it is also not so difficult. The json keystore files are in 
`/data/data/org.walleth/files/keystore` - and then you can just reimport them. Let's still keep this bug open until I close it so I prevent this in the future

**Comment by citizenserious** [comment]
Tausend Dank!

It worked, I got my key back (: did it with the app Amaze.

Thanks for your awesome work!
