### ISSUE TITLE
FC / NPE

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#85]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.walleth/org.walleth.activities.RequestActivity}: kotlin.KotlinNullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: kotlin.KotlinNullPointerException
at org.walleth.data.networks.CurrentAddressProvider.getCurrent(CurrentAddressProvider.kt:14)
at org.walleth.activities.RequestActivity.refreshQR(RequestActivity.kt:61)
at org.walleth.activities.RequestActivity.onCreate(RequestActivity.kt:42)
at android.app.Activity.performCreate(Activity.java:7000)
at android.app.Activity.performCreate(Activity.java:6991)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
... 9 more
Log:
0 D: Writing unhandled exception to: /data/user/0/org.walleth/files/0.23-1509915511599.tracedroid
1 D: current handler class=com.google.firebase.crash.FirebaseCrash$zzc
file: /data/user/0/org.walleth/files/0.23-1509915532422.tracedroid
Android Version: 8.1.0
Phone Model: Pixel
TraceDroid Version: 1.1
TraceDroid extra:
Stacktrace:
java.lang.RuntimeException: Unable to create application org.walleth.App: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.walleth/.core.GethTransactionSigner }: app is in background uid UidRecord{5531b09 u0a19 SVC  idle change:uncached procs:1 seq(0,0,0)}
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.walleth/.core.GethTransactionSigner }: app is in background uid UidRecord{5531b09 u0a19 SVC  idle change:uncached procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1518)
at android.app.ContextImpl.startService(ContextImpl.java:1474)
at android.content.ContextWrapper.startService(ContextWrapper.java:649)
at org.walleth.App.executeCodeWeWillIgnoreInTests(App.kt:135)
at org.walleth.App.onCreate(App.kt:87)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
... 8 more



```

**Comment by echorebel** [comment]
could not reproduce it again so far, maybe only new user & first session?

**Comment by ligi** [comment]
Yea - think the problem is gone once the key is created - must be a timing issue. Must make a UI-Block when the initial key is being created - might *sometimes* take a bit long - and I assume a key to be present in some places. Thanks!
